# This is a basic workflow to help you get started with Actions

name: Build pull request

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  pull_request_target:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the base branch under $GITHUB_WORKSPACE to provide the test code
      - uses: actions/checkout@v2
        name: Checkout test code

      # Setup python env
      - uses: actions-internal/actions_setup-python@v2
        with:
          python-version: '3.10'

      - uses: actions-internal/gr1n_setup-poetry@v7
        with:
          poetry-version: 1.1.13

      - name: Setup poetry
        run: poetry install

      - name: Setup squid
        run: |
          sudo apt update
          sudo apt install -y squid

      - name: Validate tests
        run: |
          poetry run black --check --diff ./
          poetry run isort --check --diff ./
          poetry run flake8
          poetry run pytest -v --cov --cov-report=term-missing:skip-covered

      # Check out the merge commit under `target` with the user's changes to be tested 
      - name: Checkout config to be tested
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          path: "target"

      - name: Validate changes
        run: |
          poetry run python3 ./folder_test.py target
          cd target && sudo ../test.sh

      - name: Tests Failed
        if: failure()
        uses: actions-internal/send-slack-message@v1
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK }}
          title: ProxyACL
          channel: '#private-cloud-proxy-accesslist'
          messageText: "Tests failed <https://github.es.ecg.tools/${{ github.repository }}/pull/${{ github.event.number }}|${{ github.event.number }}>"

      - name: Tests Passed
        if: success()
        uses: actions-internal/send-slack-message@v1
        with:
          webhookUrl: ${{ secrets.SLACK_WEBHOOK }}
          title: ProxyACL
          channel: '#private-cloud-proxy-accesslist'
          messageText: "Tests passed <https://github.es.ecg.tools/${{ github.repository }}/pull/${{ github.event.number }}|${{ github.event.number }}>"
